import { Elements } from "react-flow-renderer";
import { spaceWidth } from "./editorExamples";

export const hackdaysDemo: Elements = [
  {
    id: "oscillator",
    type: "oscillator",
    data: { label: "Oscillator" },
    position: { x: spaceWidth, y: 0 },
    className: "react-flow__node-default",
    dragHandle: ".leva-c-hwBXYF",
  },
  {
    id: "oscillator2",
    type: "oscillator",
    data: { label: "Oscillator 2" },
    position: { x: spaceWidth, y: 150 },
    className: "react-flow__node-default",
    dragHandle: ".leva-c-hwBXYF",
  },
  {
    id: "whiteNoise",
    type: "whiteNoise",
    data: { label: "White Noise" },
    position: { x: spaceWidth, y: 300 },
    className: "react-flow__node-default",
  },
  {
    id: "monoSeq",
    type: "monoSequencer",
    data: { label: "Random Seq" },
    position: { x: 0, y: 0 },
    className: "react-flow__node-default",
    dragHandle: ".leva-c-hwBXYF",
  },
  {
    id: "gain",
    type: "gain",
    dragHandle: ".leva-c-hwBXYF",
    data: { label: "Gain" },
    position: { x: spaceWidth * 2, y: 100 },
    className: "react-flow__node-default",
  },

  {
    id: "filter",
    type: "filter",
    data: { label: "Filter" },
    dragHandle: ".leva-c-hwBXYF",
    position: { x: spaceWidth * 2, y: 300 },
    className: "react-flow__node-default",
  },
  {
    id: "reverb",
    type: "reverb",
    data: { label: "Reverb" },
    dragHandle: ".leva-c-hwBXYF",
    position: { x: spaceWidth * 2, y: 0 },
    className: "react-flow__node-default",
  },
  {
    id: "visualiser",
    type: "visualiser",
    data: { label: "Oscilloscope" },
    position: { x: spaceWidth * 3, y: 100 },
    className: "react-flow__node-default",
    dragHandle: ".leva-c-hwBXYF",
  },
  {
    id: "spectroscope",
    type: "spectroscope",
    data: { label: "Spectroscope" },
    position: { x: spaceWidth * 3, y: 350 },
    className: "react-flow__node-default",
    dragHandle: ".leva-c-hwBXYF",
  },
  {
    id: "destination",
    type: "destination",
    data: { label: "Destination" },
    position: { x: spaceWidth * 4, y: 100 },
    className: "react-flow__node-default",
  },
  //wires
  {
    id: "osc-freq-to-osc",
    source: "monoSeq",
    target: "oscillator",
    type: "wire",
    sourceHandle: "out",
    targetHandle: "frequency",
  },

  {
    id: "osc-gain",
    source: "oscillator",
    target: "gain",
    type: "wire",
    targetHandle: "in",
    sourceHandle: "out",
  },
  {
    id: "ev-param-to-gain-gain",
    source: "gainGain",
    target: "gain",
    type: "wire",
    sourceHandle: "out",
    targetHandle: "gain",
  },
  {
    id: "gain-to-vis",
    source: "gain",
    target: "visualiser",
    type: "wire",
    targetHandle: "in",
    sourceHandle: "out",
  },
  {
    id: "gain-to-spectroscope",
    source: "gain",
    target: "spectroscope",
    type: "wire",
    targetHandle: "in",
    sourceHandle: "out",
  },
  {
    id: "vis-to-dest",
    source: "visualiser",
    target: "destination",
    type: "wire",
    targetHandle: "in",
    sourceHandle: "out",
  },
];
